import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@styles/globals.scss";
import { PageLayout } from "@/components/templates";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import localFont from "next/font/local";

const rattani = localFont({
  src: "./fonts/RattaniDemo.woff2",
  variable: "--font-rattani",
  display: "swap",
  fallback: ["cursive", "sans-serif"],
});
const poppinsSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinsSans.variable} ${rattani.variable}`}>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
